apiVersion: apps/v1
kind: Deployment
metadata:
  name: nirmal-deployment
  labels:
    myapp: nirmal
spec:
  replicas: 1
  selector:
    matchLabels:
      myapp: nirmal
  template:
    metadata:
      labels:
        myapp: nirmal
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
